language: cpp

compiler:
  - gcc

os:
  - linux
  - osx


env:
  matrix:
  - NODE_NVM_VERSION="0.10"
  global:
  - secure: "VaWSqPRCVqp+7bP7zYrrASXPO9Po5hX1+YaCkaGHdET9ybwejWUUPpAZ/Yfd8PrjRuzkXOWDKGL3GDbr7GbLCvD6GxXmo9WqrJMQpdzru0Gqa7p67dbA3swBA+E3QaBvcRThdPHBP7xu11+0P2K8sI7XZLGix8ebfMZZPRDfjbY="
  - secure: "ZpfehiS1S06Z9FZ1KtGOp4mdLxWj1+Kyr4kdC+525+HnVe1eMHGDyLeCK5z6vUt2G1tZ/FxGNLVQDIlwsXSbb0mOIqt/HPr1K9r3jKuPkqnrH01xiXnnrp09+NJO0E3qQlmoeyEk5mSuM5UQN1uSh7FiJC46etflhtOUs/oEjfo="

# http://about.travis-ci.org/blog/2013-11-29-postgresql-92-93-now-available/
# addons:
#   postgresql: "9.3"
# before_install:
#  - createdb template_postgis
#  - psql -c "CREATE EXTENSION postgis" template_postgis

before_install:
- COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
- PUBLISH_BINARY=false
- if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then PUBLISH_BINARY=true; fi;
- git clone https://github.com/creationix/nvm.git ../.nvm && source ../.nvm/nvm.sh
- nvm install $NODE_NVM_VERSION
- nvm use $NODE_NVM_VERSION
- node --version
- npm --version

before_script:
 - npm ls

script:
 - npm test
 - ./test/test-client.js
