language: cpp

compiler:
  - gcc

os:
  - linux
  - osx


env:
  matrix:
  - NODE_NVM_VERSION="0.10"
  global:
  - secure: "EXgVgtayyyxt7flmPhwKZIvkqfkpX1TnrX/EX7ZEQ36TuZGYYX5OXjLTtXWk9sSE6l6O3wRewpkou2PvQQpX25yOI8XYD8vBjx3ymt1lg5RS8nTDZO0XHsd0aTV7JxJCyZGCkIYXvVRPpVbLDbGwULhJe55p8YYKx/lohDB3FYM="
  - secure: "YvtR+B6yC+MxsU7tP6FCEHKLZoRfvlfwX5HSs8eAYWxqrZmIqJTbavSlj4bQ919szyQ1vZ8wTMkXd/8tCqWARTyWA8tLOHgXm/ZAlxdtdtotyZzNsbC0FmtJHF/wmaQcJ4lX2vcWWhOwtEetEULO6Hv0xGiW26aK+Jp240f6NJE="
  - secure: "FxiGeOfdx5gi6F9axPog/9ErQN7ekvSpWTLgkX5ELJGhYncl0jOyvpkJhQan/hqf6kk4SG8+JVB+R4YyN2pwh2CYZ0jNEuLvApFrIt9YRKcnMbeBkjDbAq8ZcOVm2Zjtl22N0qLWLbvUsf71AM1S9s7a8yJL/Ux62IJQxA6HDic="

# http://about.travis-ci.org/blog/2013-11-29-postgresql-92-93-now-available/
# addons:
#   postgresql: "9.3"
# before_install:
#  - createdb template_postgis
#  - psql -c "CREATE EXTENSION postgis" template_postgis

before_install:
- git clone https://github.com/creationix/nvm.git ../.nvm && source ../.nvm/nvm.sh
- nvm install $NODE_NVM_VERSION
- nvm use $NODE_NVM_VERSION
- node --version
- npm --version
- if [ $PLATFORM == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -q && sudo apt-get install -y libstdc++6; fi
- ./scripts/build-travis.sh $TRAVIS_COMMIT

install:
- npm install

before_script:
 - npm ls

script:
 - npm test
 - ./test/test-client.js

