environment:
  matrix:
    - nodejs_version: 0.10

platform:
  - x86

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - node --version
  - node -e "console.log(process.version)"
  - node -e "console.log(process.arch)"
  - npm --version
  - SET PATH=c:\python27;%PATH%
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - npm install --msvs_version=2013

build: OFF

test: OFF

test_script: OFF

deploy: OFF
