os: Visual Studio 2015

environment:
  HOME: "c:\\projects\\mapbox-studio"
  AWS_ACCESS_KEY_ID:
    secure: "yr0cfv7H8uVu2iyIn93+brMT6oEhvm9FpkJPvwGZMlA="
  AWS_SECRET_ACCESS_KEY:
    secure: "cqTj03yqur/yCYCrMI0+A2ttBJ5r7uA8Xb0i0prEcM7lDLczYssPdp3DnqUnvIPN"
  matrix:
    - NODE_VERSION: 0.10.33
      platform: x64
    - NODE_VERSION: 0.10.33
      platform: x86
    - NODE_VERSION: 0.12.7
      platform: x64
    - NODE_VERSION: 0.12.7
      platform: x86

shallow_clone: true

install:
  - CALL scripts\build-appveyor.bat

build: off
test: off
deploy: off
