os: Visual Studio 2015

environment:
  HOME: "c:\\projects\\tm2"
  AWS_ACCESS_KEY_ID:
    secure: "yr0cfv7H8uVu2iyIn93+brMT6oEhvm9FpkJPvwGZMlA="
  AWS_SECRET_ACCESS_KEY:
    secure: "cqTj03yqur/yCYCrMI0+A2ttBJ5r7uA8Xb0i0prEcM7lDLczYssPdp3DnqUnvIPN"
  matrix:
    - NODE_VERSION: 0.12.7
      platform: x64
    - NODE_VERSION: 0.12.7
      platform: x86

shallow_clone: true

install:
  # find and remove default node.exe to avoid conflicts
  - node -e "console.log(process.execPath)" > node_path.txt
  - SET /p NODE_EXE_PATH=<node_path.txt
  - del node_path.txt
  - del /q /s "%NODE_EXE_PATH%"
  # add local node to path
  - SET PATH=%CD%;%PATH%;
  - SET ARCHPATH=
  - if %platform% == x64 (SET ARCHPATH=x64/)
  - ps: Write-Output "fetching https://mapbox.s3.amazonaws.com/node-cpp11/v${env:NODE_VERSION}/${env:ARCHPATH}node.exe"
  - ps: Start-FileDownload "https://mapbox.s3.amazonaws.com/node-cpp11/v${env:NODE_VERSION}/${env:ARCHPATH}node.exe"
  - node -e "console.log(process.argv,process.execPath,process.arch)"
  - npm -v
  - npm install --fallback-to-build=false --toolset=v140
  # put dumpbin on path: required by check_shared_libs.py
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin;%PATH%
  - python test\check_shared_libs.py .\
  - npm test
  - node test/test-client.js

build: OFF
test: OFF
deploy: OFF
