environment:
  HOME: "c:\\projects\\tm2"
  AWS_ACCESS_KEY_ID:
    secure: "yr0cfv7H8uVu2iyIn93+brMT6oEhvm9FpkJPvwGZMlA="
  AWS_SECRET_ACCESS_KEY:
    secure: "cqTj03yqur/yCYCrMI0+A2ttBJ5r7uA8Xb0i0prEcM7lDLczYssPdp3DnqUnvIPN"
  matrix:
    - NODE_VERSION: 0.10.33

shallow_clone: true

platform:
  - x64

install:
  - echo %platform%
  - ps: Start-FileDownload "https://mapbox.s3.amazonaws.com/node-cpp11/vcredist_$env:platform.exe"
  - .\vcredist_%platform%.exe /q /norestart
  - ps: Start-FileDownload "https://mapbox.s3.amazonaws.com/node-cpp11/v$env:NODE_VERSION/$env:platform/node.exe"
  # add local node to PATH
  - SET PATH=%CD%;%PATH%;
  # make sure we are running local node
  - node -e "console.log(process.execPath)"
  - node -e "console.log(process.arch)"
  - node -v
  - npm install --toolset=v140
  - npm test
  - node test/test-client.js

build: OFF
test: OFF
test_script: OFF
deploy: OFF
